# Generated by Django 4.1.6 on 2023-02-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1024, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('access_token', models.CharField(max_length=1024)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=1024)),
            ],
        ),
    ]
