# Generated by Django 4.1.6 on 2023-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oath_tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_tokenZ', models.CharField(max_length=100, unique=True)),
                ('oauth_token_secretZ', models.CharField(max_length=100, unique=True)),
                ('oauth_callback_confirmedZ', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
